version: '3.8'

services:
  # 3 Zookeeper ноды
  zookeeper1:
    image: zookeeper:3.9
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper1_data:/data
    restart: always

  # 3 Zookeeper ноды
  zookeeper2:
    image: zookeeper:3.9
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper2_data:/data
    restart: always

  # 3 Zookeeper ноды
  zookeeper3:
    image: zookeeper:3.9
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper3_data:/data
    restart: always

  # SHARD 1
  clickhouse-01:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse-01
    hostname: clickhouse-01
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_01_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
      - ./config/ch1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on: [zookeeper1, zookeeper2, zookeeper3]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  clickhouse-02:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse-02
    hostname: clickhouse-02
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_02_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
      - ./config/ch2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on: [zookeeper1, zookeeper2, zookeeper3]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  # SHARD 2
  clickhouse-03:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse-03
    hostname: clickhouse-03
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - clickhouse_03_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
      - ./config/ch3/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on: [zookeeper1, zookeeper2, zookeeper3]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  clickhouse-04:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse-04
    hostname: clickhouse-04
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - clickhouse_04_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
      - ./config/ch4/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on: [zookeeper1, zookeeper2, zookeeper3]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

volumes:
  zookeeper1_data:
  zookeeper2_data:
  zookeeper3_data:
  clickhouse_01_data:
  clickhouse_02_data:
  clickhouse_03_data:
  clickhouse_04_data: